production: &ldap_defaults
  hostname: localhost
  basedn: ou=users,dc=test
  auth: false
  port: 3897
  username_ldap_attribute: uid
  attributes:
      - mail
      - uid
      - cn


test:
  <<: *ldap_defaults

development:
  <<: *ldap_defaults
