production: &ldap_defaults
  hostname: <%= ENV['HOSTNAME'] || 'localhost' %>
  hosts:
      - - localhost
        - 3897
  basedn: ou=users,dc=test
  auth: false
  port: <%= ENV['PORT'] || '3897' %>
  username_ldap_attribute:
      - mail
      - uid
  attributes:
      - mail
      - uid
      - cn

test:
  <<: *ldap_defaults

development:
  <<: *ldap_defaults
